/**
 * Famecipe.Microservice.Recipes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Recipe { 
    identifier?: string | null;
    name?: string | null;
    image?: string | null;
    ingredients?: Array<string> | null;
    equipment?: Array<string> | null;
    directions?: Array<string> | null;
    whenUpdatedUTC?: string | null;
}

